######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 21 11:17:43 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT+=network
# Input
HEADERS += client.h
SOURCES += client.cpp main.cpp
