######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 21 11:16:40 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT+=network
# Input
HEADERS += dialog.h timeserver.h timethread.h
SOURCES += dialog.cpp main.cpp timeserver.cpp timethread.cpp
